### ISSUE TITLE
App crashes when trying to login with my created account

### ISSUE THREAD

**Issue by mcyusuf** [FalinwaLimited/android-odoo-standard-expense#1]
#### Expected behavior
I created a new account from the link in the app, then I return to the app to login and make use of it. The login is expected to be successful.
#### Actual behavior
After creating an account, and trying to login with my odoo instance on the app, it crashes after a while after clicking on the login button
#### How to reproduce
1. Use the `Create account` button to create an odoo instance.
2. After successful account creation, return to app main page
3. Input email and password in respective fields
4. Click the `ACCEPT & LOGIN` button to login your instance
5. The app crashes while trying to load the login

#### Device details
* Tecno k7 running on Nougat 7.0.

#### Logcat
```
05-30 06:31:55.464 I/ActivityManager(800): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin (has extras)} from uid 10022 on display 0
05-30 06:31:55.503 I/BufferQueueConsumer(224): [Starting com.falinwa.android.odoo_open_expense](this:0xad1b8000,id:1183,api:0,p:-1,c:224) setConsumerName: Starting com.falinwa.android.odoo_open_expense
05-30 06:31:55.503 I/BufferQueueConsumer(224): [Starting com.falinwa.android.odoo_open_expense](this:0xad1b8000,id:1183,api:0,p:-1,c:224) setDefaultBufferSize: width=1 height=1
05-30 06:31:55.515 I/BufferQueueConsumer(224): [Starting com.falinwa.android.odoo_open_expense](this:0xad1b8000,id:1183,api:0,p:-1,c:224) setDefaultBufferSize: width=720 height=1280
05-30 06:31:55.523 I/ActivityManager(800): Start proc 6947:com.falinwa.android.odoo_open_expense/u0a235 for activity com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin
05-30 06:31:55.528 I/BufferQueueProducer(224): [Starting com.falinwa.android.odoo_open_expense](this:0xad1b8000,id:1183,api:2,p:800,c:224) connect(P): api=2 producer=(800:system_server) producerControlledByApp=false
05-30 06:31:55.529 I/BufferQueueProducer(224): [Starting com.falinwa.android.odoo_open_expense](this:0xad1b8000,id:1183,api:2,p:800,c:224) new GraphicBuffer needed
05-30 06:31:55.567 I/libPerfService(800): [perfNotifyAppState] foreground:com.falinwa.android.odoo_open_expense, pid:6947
05-30 06:31:55.567 I/PPS     (800): [PPSNotifyAppState] pack:com.falinwa.android.odoo_open_expense, com:com.odoo.core.account.OdooLogin, state:1,ActiveCount = 1
05-30 06:31:55.567 I/PPS     (800): [PPSNotifyAppState] nPackNum:102, pack:com.falinwa.android.odoo_open_expense, com:com.odoo.core.account.OdooLogin, state:1, pid:6947, last_boost_tid:6947
05-30 06:31:55.630 W/System  (6947): ClassLoader referenced unknown path: /data/app/com.falinwa.android.odoo_open_expense-1/lib/arm
05-30 06:31:56.584 I/BufferQueueConsumer(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:0,p:-1,c:224) setConsumerName: com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin
05-30 06:31:56.584 I/BufferQueueConsumer(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:0,p:-1,c:224) setDefaultBufferSize: width=1 height=1
05-30 06:31:56.604 I/BufferQueueConsumer(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:0,p:-1,c:224) setDefaultBufferSize: width=720 height=1280
05-30 06:31:56.623 E/        (6947): appName=com.falinwa.android.odoo_open_expense, acAppName=/system/bin/surfaceflinger
05-30 06:31:56.658 I/BufferQueueProducer(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:1,p:6947,c:224) connect(P): api=1 producer=(6947:com.falinwa.android.odoo_open_expense) producerControlledByApp=true
05-30 06:31:56.660 I/BufferQueueProducer(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:1,p:6947,c:224) setMaxDequeuedBufferCount: maxDequeuedBuffers = 3
05-30 06:31:56.669 I/BufferQueueProducer(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:1,p:6947,c:224) new GraphicBuffer needed
05-30 06:31:56.751 I/ActivityManager(800): Displayed com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin: +1s257ms
05-30 06:31:56.760 I/BufferQueueProducer(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:1,p:6947,c:224) new GraphicBuffer needed
05-30 06:31:56.799 I/WindowManager(800): Destroying surface Surface(name=Starting com.falinwa.android.odoo_open_expense) called by com.android.server.wm.WindowStateAnimator.destroySurface:2137 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:948 com.android.server.wm.WindowState.destroyOrSaveSurface:2113 com.android.server.wm.AppWindowToken.destroySurfaces:372 com.android.server.wm.WindowStateAnimator.finishExit:586 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:512 com.android.server.wm.WindowAnimator.updateWindowsLocked:319 com.android.server.wm.WindowAnimator.animateLocked:720 
05-30 06:31:56.801 I/BufferQueueProducer(224): [Starting com.falinwa.android.odoo_open_expense](this:0xad1b8000,id:1183,api:2,p:-1,c:224) disconnect(P): api 2
05-30 06:31:56.801 I/BufferQueueConsumer(224): [Starting com.falinwa.android.odoo_open_expense](this:0xad1b8000,id:1183,api:2,p:-1,c:224) getReleasedBuffers: returning mask 0xffffffffffffffff
05-30 06:31:56.815 I/BufferQueueConsumer(224): [Starting com.falinwa.android.odoo_open_expense](this:0xad1b8000,id:1183,api:2,p:-1,c:-1) disconnect(C)
05-30 06:31:56.815 I/BufferQueue(224): [Starting com.falinwa.android.odoo_open_expense](this:0xad1b8000,id:1183,api:2,p:-1,c:-1) ~BufferQueueCore
05-30 06:31:56.880 I/LatinIme(913): onActivate() : EditorInfo = Package = com.falinwa.android.odoo_open_expense : Type = Text : Learning = Disable : Suggestion = Show : AutoCorrection = Disable : Microphone = Show : Incognito = Disable
05-30 06:31:56.940 W/Conv2QueryExtension(913): Conv2Query not enabled due to current app [com.falinwa.android.odoo_open_expense] not in whitelist
05-30 06:31:57.735 I/BufferQueueProducer(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:1,p:6947,c:224) new GraphicBuffer needed
05-30 06:31:57.748 I/BufferQueueProducer(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:1,p:6947,c:224) queueBuffer: fps=1.94 dur=1032.83 max=972.04 min=60.79
05-30 06:31:59.350 I/BufferQueueProducer(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:1,p:6947,c:224) queueBuffer: fps=10.62 dur=1601.32 max=891.11 min=16.21
05-30 06:32:00.356 I/BufferQueueProducer(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:1,p:6947,c:224) queueBuffer: fps=1.99 dur=1006.49 max=724.83 min=281.66
05-30 06:32:00.861 W/Conv2QueryExtension(913): Conv2Query not enabled due to current app [com.falinwa.android.odoo_open_expense] not in whitelist
05-30 06:32:01.830 I/BufferQueueProducer(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:1,p:6947,c:224) queueBuffer: fps=1.36 dur=1473.94 max=1004.31 min=469.63
05-30 06:32:03.267 I/BufferQueueProducer(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:1,p:6947,c:224) queueBuffer: fps=2.78 dur=1437.22 max=439.76 min=175.47
05-30 06:32:04.268 I/BufferQueueProducer(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:1,p:6947,c:224) queueBuffer: fps=1.00 dur=1000.75 max=1000.75 min=1000.75
05-30 06:32:05.340 I/BufferQueueProducer(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:1,p:6947,c:224) queueBuffer: fps=2.80 dur=1072.14 max=755.32 min=105.73
05-30 06:32:06.344 I/BufferQueueProducer(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:1,p:6947,c:224) queueBuffer: fps=1.00 dur=1003.32 max=1003.32 min=1003.32
05-30 06:32:07.958 I/BufferQueueProducer(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:1,p:6947,c:224) queueBuffer: fps=1.86 dur=1614.11 max=1001.13 min=120.43
05-30 06:32:08.963 I/BufferQueueProducer(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:1,p:6947,c:224) queueBuffer: fps=21.88 dur=1005.57 max=492.79 min=6.42
05-30 06:32:09.979 I/BufferQueueProducer(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:1,p:6947,c:224) queueBuffer: fps=56.13 dur=1015.52 max=36.52 min=11.78
05-30 06:32:10.980 I/BufferQueueProducer(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:1,p:6947,c:224) queueBuffer: fps=56.93 dur=1001.27 max=23.07 min=11.55
05-30 06:32:11.925 E/AndroidRuntime(6947): Process: com.falinwa.android.odoo_open_expense, PID: 6947
05-30 06:32:11.925 E/AndroidRuntime(6947): 	at com.odoo.core.rpc.helper.OdooVersion.parseVersion(OdooVersion.java:74)
05-30 06:32:11.925 E/AndroidRuntime(6947): 	at com.odoo.core.rpc.wrapper.OdooWrapper$3.onResponse(OdooWrapper.java:275)
05-30 06:32:11.925 E/AndroidRuntime(6947): 	at com.odoo.core.rpc.wrapper.OdooWrapper.onResponse(OdooWrapper.java:993)
05-30 06:32:11.925 E/AndroidRuntime(6947): 	at com.odoo.core.rpc.wrapper.OdooWrapper.onResponse(OdooWrapper.java:72)
05-30 06:32:11.935 W/ActivityManager(800):   Force finishing activity com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin
05-30 06:32:12.025 I/AEE_AED (7030): [preset_info] pid: 6947, tid: -1361051648, name: UNKNOWN  >>> com.falinwa.android.odoo_open_expense <<<
05-30 06:32:12.103 I/BufferQueueConsumer(224): [Application Error: com.falinwa.android.odoo_open_expense](this:0xad1ba000,id:1186,api:0,p:-1,c:224) setConsumerName: Application Error: com.falinwa.android.odoo_open_expense
05-30 06:32:12.104 I/BufferQueueConsumer(224): [Application Error: com.falinwa.android.odoo_open_expense](this:0xad1ba000,id:1186,api:0,p:-1,c:224) setDefaultBufferSize: width=129 height=129
05-30 06:32:12.118 I/BufferQueueConsumer(224): [Application Error: com.falinwa.android.odoo_open_expense](this:0xad1ba000,id:1186,api:0,p:-1,c:224) setDefaultBufferSize: width=812 height=512
05-30 06:32:12.127 I/BufferQueueProducer(224): [Application Error: com.falinwa.android.odoo_open_expense](this:0xad1ba000,id:1186,api:1,p:800,c:224) connect(P): api=1 producer=(800:system_server) producerControlledByApp=false
05-30 06:32:12.132 I/BufferQueueProducer(224): [Application Error: com.falinwa.android.odoo_open_expense](this:0xad1ba000,id:1186,api:1,p:800,c:224) setMaxDequeuedBufferCount: maxDequeuedBuffers = 3
05-30 06:32:12.141 I/BufferQueueProducer(224): [Application Error: com.falinwa.android.odoo_open_expense](this:0xad1ba000,id:1186,api:1,p:800,c:224) new GraphicBuffer needed
05-30 06:32:12.158 I/BufferQueueProducer(224): [Application Error: com.falinwa.android.odoo_open_expense](this:0xad1ba000,id:1186,api:1,p:800,c:224) new GraphicBuffer needed
05-30 06:32:12.459 W/ActivityManager(800): Activity pause timeout for ActivityRecord{6d668ff u0 com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin t3577 f}
05-30 06:32:12.459 I/PPS     (800): [PPSNotifyAppState] pack:com.falinwa.android.odoo_open_expense, com:com.odoo.core.account.OdooLogin, state:0,ActiveCount = 0
05-30 06:32:12.459 I/PPS     (800): [PPSNotifyAppState] nPackNum:102, pack:com.falinwa.android.odoo_open_expense, com:com.odoo.core.account.OdooLogin, state:0, pid:6947, last_boost_tid:6947
05-30 06:32:14.584 W/ActivityManager(800):   Force finishing activity com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin
05-30 06:32:14.588 I/BufferQueueProducer(224): [Application Error: com.falinwa.android.odoo_open_expense](this:0xad1ba000,id:1186,api:1,p:-1,c:224) disconnect(P): api 1
05-30 06:32:14.589 I/BufferQueueConsumer(224): [Application Error: com.falinwa.android.odoo_open_expense](this:0xad1ba000,id:1186,api:1,p:-1,c:224) getReleasedBuffers: returning mask 0xffffffffffffffff
05-30 06:32:14.593 I/WindowManager(800): Destroying surface Surface(name=com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin) called by com.android.server.wm.WindowStateAnimator.destroySurface:2137 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:948 com.android.server.wm.WindowState.removeLocked:1469 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2678 com.android.server.wm.WindowManagerService.removeWindowLocked:2626 com.android.server.wm.WindowManagerService.removeWindowLocked:2489 com.android.server.wm.AppWindowToken.removeAllWindows:539 com.android.server.wm.AppWindowToken.removeAppFromTaskLocked:335 
05-30 06:32:14.595 I/BufferQueueConsumer(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:1,p:6947,c:-1) disconnect(C)
05-30 06:32:14.599 I/ActivityManager(800): Killing 6947:com.falinwa.android.odoo_open_expense/u0a235 (adj 900): crash
05-30 06:32:14.633 W/ViewRootImpl[odoo_open_expense](800): Dropping event due to root view being removed: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=203.6921, y[0]=-46.33255, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=2, eventTime=32624150, downTime=32624121, deviceId=2, source=0x1002 }
05-30 06:32:14.651 I/WindowManager(800): Destroying surface Surface(name=Application Error: com.falinwa.android.odoo_open_expense) called by com.android.server.wm.WindowStateAnimator.destroySurface:2137 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:948 com.android.server.wm.WindowState.destroyOrSaveSurface:2113 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementInner:434 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:235 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:183 com.android.server.wm.WindowManagerService$H.handleMessage:8464 android.os.Handler.dispatchMessage:110 
05-30 06:32:14.666 I/BufferQueueConsumer(224): [Application Error: com.falinwa.android.odoo_open_expense](this:0xad1ba000,id:1186,api:1,p:-1,c:-1) disconnect(C)
05-30 06:32:14.666 I/BufferQueue(224): [Application Error: com.falinwa.android.odoo_open_expense](this:0xad1ba000,id:1186,api:1,p:-1,c:-1) ~BufferQueueCore
05-30 06:32:14.688 I/BufferQueueProducer(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:1,p:-1,c:-1) disconnect(P): api 1
05-30 06:32:14.689 I/BufferQueue(224): [com.falinwa.android.odoo_open_expense/com.odoo.core.account.OdooLogin](this:0xad1df000,id:1184,api:1,p:-1,c:-1) ~BufferQueueCore
```

#### Recording of the bug
![20180530_063032](https://user-images.githubusercontent.com/35164646/40701251-30c31736-63d5-11e8-9cd0-b648137f894d.gif)

**Comment by RahmatNS** [comment]
hi @mcyusuf 
currently we only support for odoo v10.
for now, odoo.com is v11 that we are not support yet.

later we will working on it. so you can wait for future update or host your odoo v10 instance by yourself.

**Comment by mcyusuf** [comment]
Okay, I would wait for future updates on that. Thanks for the reply.

**Comment by RahmatNS** [comment]
hi @mcyusuf 

fyi,
we just add new commit in new branch (v11) and tested that it work well in odoo saas.
